### ISSUE TITLE
test suite fails with openssl 1.1.1e

### ISSUE THREAD

**Issue by FelixSchwarz** [cedadev/ndg_httpsclient#22]
The test suite fails after upgrading openssl to 1.1.1e on Fedora rawhide ("Fedora 33"):

    ======================================================================
    ERROR: test02_fetch_from_url (__main__.TestUtilsModule)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./test_utils.py", line 32, in test02_fetch_from_url
        res = fetch_from_url(Constants.TEST_URI, config)
      File "/builddir/build/BUILD/ndg_httpsclient-0.5.1/ndg/httpsclient/utils.py", line 100, in fetch_from_url
        raise URLFetchError(return_message)
    ndg.httpsclient.utils.URLFetchError: Error: [('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')]
    ======================================================================
    FAIL: test03_open_url (__main__.TestUtilsModule)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "./test_utils.py", line 38, in test03_open_url
        self.assertEqual(res[0], 200,
    AssertionError: 0 != 200 : open_url for 'https://localhost:4443' failed
    ----------------------------------------------------------------------

This might be related/similar to another bug report for urllib3: [unexected eof with OpenSSL 1.1.1e #1825](https://github.com/urllib3/urllib3/issues/1825).

Downstream Fedora issue will complete build logs: https://bugzilla.redhat.com/show_bug.cgi?id=1815903

**Comment by FelixSchwarz** [comment]
The openssl change was reverted so you don't have to solve this right now. I'm not sure yet if the change will reappear in a future version openssl and/or if Python will be adapted to handle this.
